{
 "title": "kubepark",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Park", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Datetime (Live)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "stream": { "channel": "stream/kubepark-time", "filter": "park_time" } }
   ]
  },
  {
   "title": "Money (Prometheus)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (container) (park_money{container=\"park\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Money (Live)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "stream": { "channel": "stream/kubepark-time", "filter": "park_money" } }
   ]
  },
  {
   "title": "Opening hour",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (container) (park_opens_at{container=\"park\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shutdown",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (container) (park_is_closed{container=\"park\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Closing hour",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (container) (park_closes_at{container=\"park\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Entrance Fee",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (container) (park_entrance_fee{container=\"park\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Park logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"park\"} |= ``"
    }
   ]
  },
  { "title": "Guests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Guests In Park",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_active{exported_namespace=\"guests\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Guests for the day",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_info{exported_namespace=\"guests\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Guest logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"guests\"} | line_format `[{{.pod}}] {{__line__}}`"
    }
   ]
  },
  {
   "title": "Attractions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true
  },
  {
   "title": "Attractions logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"attractions\"}"
    }
   ]
  }
 ]
}