apiVersion: apps/v1
kind: Deployment
metadata:
  name: park
  namespace: park
  labels:
    app.kubernetes.io/name: kubepark
    app.kubernetes.io/component: park
    app: park
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: park
  template:
    metadata:
      labels:
        app: park
        app.kubernetes.io/name: kubepark
        app.kubernetes.io/component: park
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: park
          image: localhost:5001/kubepark:latest
          ports:
            - containerPort: 80
              name: http
            - containerPort: 9000
              name: metrics
          command: ["park"]
          args:
            - "--self-url"
            - "http://park.park.svc.cluster.local."
            - "--image"
            - "localhost:5001/kubepark:latest"
            - "--opens-at"
            - "8"
            - "--closes-at"
            - "20"
            - "--log-level"
            - "debug"
          livenessProbe:
            httpGet:
              path: /park-status
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /park-status
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: park
  namespace: park
  labels:
    app.kubernetes.io/name: kubepark
    app.kubernetes.io/component: park
    app: park
spec:
  selector:
    app: park
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: metrics
      protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30090
  type: NodePort
