# PersistentVolume for Park
apiVersion: v1
kind: PersistentVolume
metadata:
  name: park-pv
  labels:
    app.kubernetes.io/name: kubepark
    app.kubernetes.io/component: park
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /tmp/kubepark/park
    type: DirectoryOrCreate

---
# PersistentVolumeClaim for Park
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: park-pvc
  namespace: park
  labels:
    app.kubernetes.io/name: kubepark
    app.kubernetes.io/component: park
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: park
  namespace: park
  labels:
    app.kubernetes.io/name: kubepark
    app.kubernetes.io/component: park
    app: park
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: park
  template:
    metadata:
      labels:
        app: park
        app.kubernetes.io/name: kubepark
        app.kubernetes.io/component: park
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9000"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: volume-permissions
          image: busybox:1.35
          command:
            ["sh", "-c", "chown -R 1000:1000 /data && chmod -R 755 /data"]
          volumeMounts:
            - name: park-storage
              mountPath: /data
          securityContext:
            runAsUser: 0
      containers:
        - name: park
          image: localhost:5001/kubepark:latest
          ports:
            - containerPort: 80
              name: http
            - containerPort: 9000
              name: metrics
          command: ["park"]
          args:
            - "--self-url"
            - "http://park.park.svc.cluster.local."
            - "--image"
            - "localhost:5001/kubepark:latest"
            - "--opens-at"
            - "8"
            - "--closes-at"
            - "20"
            - "--log-level"
            - "debug"
            - "--volume"
            - "/data"
          volumeMounts:
            - name: park-storage
              mountPath: /data
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          livenessProbe:
            httpGet:
              path: /park-status
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /park-status
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: park-storage
          persistentVolumeClaim:
            claimName: park-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: park
  namespace: park
  labels:
    app.kubernetes.io/name: kubepark
    app.kubernetes.io/component: park
    app: park
spec:
  selector:
    app: park
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: metrics
      protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
