# PersistentVolume for Carousel
apiVersion: v1
kind: PersistentVolume
metadata:
  name: carousel-pv-${INSTANCE_ID}
  labels:
    app.kubernetes.io/name: kubepark
    app.kubernetes.io/component: attraction
    app.kubernetes.io/instance: carousel-${INSTANCE_ID}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /tmp/kubepark/attractions/carousel-${INSTANCE_ID}
    type: DirectoryOrCreate

---
# PersistentVolumeClaim for Carousel
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: carousel-pvc-${INSTANCE_ID}
  namespace: attractions
  labels:
    app.kubernetes.io/name: kubepark
    app.kubernetes.io/component: attraction
    app.kubernetes.io/instance: carousel-${INSTANCE_ID}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carousel-${INSTANCE_ID}
  namespace: attractions
  labels:
    app.kubernetes.io/name: kubepark
    app.kubernetes.io/component: attraction
    app.kubernetes.io/instance: carousel-${INSTANCE_ID}
    app: carousel-${INSTANCE_ID}
    attraction: carousel
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: carousel-${INSTANCE_ID}
  template:
    metadata:
      labels:
        app: carousel-${INSTANCE_ID}
        app.kubernetes.io/name: kubepark
        app.kubernetes.io/component: attraction
        app.kubernetes.io/instance: carousel-${INSTANCE_ID}
        attraction: carousel
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9000"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: volume-permissions
          image: busybox:1.35
          command:
            ["sh", "-c", "chown -R 1000:1000 /data && chmod -R 755 /data"]
          volumeMounts:
            - name: carousel-storage-${INSTANCE_ID}
              mountPath: /data
          securityContext:
            runAsUser: 0
      containers:
        - name: carousel
          image: localhost:5001/kubepark:latest
          ports:
            - containerPort: 80
              name: http
            - containerPort: 9000
              name: metrics
          command: ["carousel"]
          args:
            - "--park-url"
            - "http://park.park.svc.cluster.local."
            - "--volume"
            - "/data"
          volumeMounts:
            - name: carousel-storage-${INSTANCE_ID}
              mountPath: /data
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          livenessProbe:
            httpGet:
              path: /attraction-status
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /attraction-status
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: carousel-storage-${INSTANCE_ID}
          persistentVolumeClaim:
            claimName: carousel-pvc-${INSTANCE_ID}
---
apiVersion: v1
kind: Service
metadata:
  name: carousel-${INSTANCE_ID}
  namespace: attractions
  labels:
    app.kubernetes.io/name: kubepark
    app.kubernetes.io/component: attraction
    app.kubernetes.io/instance: carousel-${INSTANCE_ID}
    app: carousel-${INSTANCE_ID}
    attraction: carousel
spec:
  selector:
    app: carousel-${INSTANCE_ID}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: metrics
      protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
