apiVersion: apps/v1
kind: Deployment
metadata:
  name: restroom
  namespace: attractions
  labels:
    app.kubernetes.io/name: kubepark
    app.kubernetes.io/component: attraction
    app.kubernetes.io/instance: restroom
    app: restroom
    attraction: restroom
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: restroom
  template:
    metadata:
      labels:
        app: restroom
        app.kubernetes.io/name: kubepark
        app.kubernetes.io/component: attraction
        app.kubernetes.io/instance: restroom
        attraction: restroom
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: restroom
          image: localhost:5001/kubepark:latest
          ports:
            - containerPort: 80
              name: http
            - containerPort: 9000
              name: metrics
          command: ["restroom"]
          args:
            - "--park-url"
            - "http://park.park.svc.cluster.local."
          livenessProbe:
            httpGet:
              path: /attraction-status
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /attraction-status
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: restroom
  namespace: attractions
  labels:
    app.kubernetes.io/name: kubepark
    app.kubernetes.io/component: attraction
    app.kubernetes.io/instance: restroom
    app: restroom
    attraction: restroom
spec:
  selector:
    app: restroom
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30082
    - name: metrics
      protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30092
  type: NodePort
