package metrics

import (
	"github.com/prometheus/client_golang/prometheus"
)

// ParkMetrics contains all metrics specific to the main kubepark simulator
var (
	Cash = prometheus.NewGauge(prometheus.GaugeOpts{
		Name: "kubepark_cash",
		Help: "Current cash amount in the park",
	})

	Time = prometheus.NewGauge(prometheus.GaugeOpts{
		Name: "kubepark_time",
		Help: "Current time in the park (Unix timestamp)",
	})

	EntranceFee = prometheus.NewGauge(prometheus.GaugeOpts{
		Name: "kubepark_entrance_fee",
		Help: "Current entrance fee",
	})

	OpensAt = prometheus.NewGauge(prometheus.GaugeOpts{
		Name: "kubepark_opens_at",
		Help: "Hour at which the park opens",
	})

	ClosesAt = prometheus.NewGauge(prometheus.GaugeOpts{
		Name: "kubepark_closes_at",
		Help: "Hour at which the park closes",
	})

	IsParkClosed = prometheus.NewGauge(prometheus.GaugeOpts{
		Name: "kubepark_is_closed",
		Help: "Whether the park is closed (1) or open (0)",
	})

	Guests = prometheus.NewGauge(prometheus.GaugeOpts{
		Name: "kubepark_guests",
		Help: "Current number of guests in the park",
	})

	ParkAttempts = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "attempts",
			Help: "Number of attempts to enter the park",
		},
		[]string{"success", "reason"},
	)
)

// AttractionMetrics contains all metrics common to attractions
var (
	Revenue = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "revenue",
		Help: "Total revenue generated by the attraction",
	})

	Fee = prometheus.NewGauge(prometheus.GaugeOpts{
		Name: "fee",
		Help: "Current fee for using the attraction",
	})

	IsAttractionClosed = prometheus.NewGauge(prometheus.GaugeOpts{
		Name: "is_closed",
		Help: "Whether the attraction is closed (1) or open (0)",
	})

	AttractionAttempts = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "attempts",
			Help: "Number of attempts to use the attraction",
		},
		[]string{"success", "reason"},
	)
)

// RegisterParkMetrics registers all park-specific metrics
func RegisterParkMetrics() {
	prometheus.MustRegister(Cash)
	prometheus.MustRegister(Time)
	prometheus.MustRegister(EntranceFee)
	prometheus.MustRegister(OpensAt)
	prometheus.MustRegister(ClosesAt)
	prometheus.MustRegister(IsParkClosed)
	prometheus.MustRegister(Guests)
	prometheus.MustRegister(ParkAttempts)
}

// RegisterAttractionMetrics registers all attraction-specific metrics
func RegisterAttractionMetrics() {
	prometheus.MustRegister(Revenue)
	prometheus.MustRegister(Fee)
	prometheus.MustRegister(IsAttractionClosed)
	prometheus.MustRegister(AttractionAttempts)
}
